language: node_js
node_js: 10

jobs:
  include:
    - stage: build
      script:
        - npm run build
        - ls

    - stage: deploy
      before_script:
        - git config --global user.name 'whatwewant'
        - git config --global user.email 'tobewhatwewant@gmail.com'
        - git clone --branch gh-pages https://github.com/${TRAVIS_REPO_SLUG} gh-pages
      script:
        - echo "build deploy"
        - npm run build
        - ls
      after_success:
        - cp -rf dist/* gh-pages
        - cp CNAME gh-pages
        - cd gh-pages
        - git add --all .
        - git commit -a -m ':sparkles:(TravisCI) automatically update from travis_ci (${TRAVIS_TAG})'
        - git push --quiet --force "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" gh-pages:gh-pages
      deploy:
        provider: script
        script:
          - echo "deploy to gh-pages."
        skip_cleanup: true
        on:
          branch: master
