language: node_js
node_js: 10

jobs:
  include:
    # - stage: build
    #  script:
    #    - echo "build dist"
    #    - npm run build

    - stage: deploy
      script:
        - echo "build deploy for test multi stage"
        - npm run build

    - stage: deploy

      before_script:
        - git config --global user.name 'whatwewant'
        - git config --global user.email 'tobewhatwewant@gmail.com'
        - git clone --branch gh-pages https://github.com/${TRAVIS_REPO_SLUG} gh-pages

      script:
        - echo "build deploy for gh-pages"
        - npm run build

      deploy:
        - provider: script
          script:
            - echo "deploy to gh-pages."
            - cp -rf dist/* gh-pages
            - cp CNAME gh-pages
            - cd gh-pages
            - git add --all .
            - git commit -a -m ':sparkles:(TravisCI) automatically update from travis_ci ${TRAVIS_TAG}'
            - git push --quiet "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" gh-pages:gh-pages
          skip_cleanup: true
          on:
            tags: true
            # branch: master

#        - provider: heroku
#            # branch: master
#          skip_cleanup: true
#          api_key: "YOUR API KEY"
#          on:
#            branch: heroku
#
#        - provider: npm
#          skip_cleanup: true
#          on:
#            branch: npm
#            # tags: true
