language: node_js
node_js:
  - 8

# after_success: npm run build

jobs:
  include:
    - stage: gh-pages
      node_js: 10
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        before_script:
          - git config --global user.name 'whatwewant'
          - git config --global user.email 'tobewhatwewant@gmail.com'
          - git clone --branch gh-pages https://github.com/${TRAVIS_REPO_SLUG} gh-pages
        script:
          - echo "deploy to gh-pages"
          - npm run build
        after_success:
          - cp -rf dist/* gh-pages
          - cp CNAME gh-pages
          - cd gh-pages
          - git add --all .
          - git commit -a -m ':sparkles:(TravisCI) automatically update from travis_ci (${TRAVIS_TAG})'
          - git push --quiet --force "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}" gh-pages:gh-pages
